// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "defaultSiteId": string;
      "globalPromptTemplate": string;
      "defaultPromptTemplateId": string;
      "promptTemplatesJson": string;
      "siteProfilesJson": string;
      "chromeAppPath": string;
      "confirmBeforeSend": boolean;
      "fillPromptEnabled": boolean;
      "showUsageHints": boolean;
    };
  }
}
